Proekt2/Models/CustomMade.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Proekt2.Models
{
    public class CustomMade
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string ImgURL { get; set; }

        public int Price { get; set; }

        public string Processor { get; set; }

        public string MotherBoard { get; set; }

        public string Storage { get; set; }

        [Display(Name = "Power Supply")]
        public string PowerSupply { get; set; }

        public string RAM { get; set; }

        [Display(Name = "Graphics card")]
        public string GraphicsCard { get; set; }

        public string Case { get; set; }
    }
}

Proekt2/Controllers/CustomMadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Proekt2.Models
{
    public class CustomMadesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CustomMades
        public ActionResult Index()
        {
            return View(db.customMades.ToList());
        }

        public ActionResult PreBuiltPC()
        {
            return PartialView(db.customMades.ToList());
        }

        // GET: CustomMades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomMade customMade = db.customMades.Find(id);
            if (customMade == null)
            {
                return HttpNotFound();
            }
            return View(customMade);
        }

        [Authorize(Roles = "Administrator, Seller")]
        // GET: CustomMades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomMades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Seller")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ImgURL,Price,Processor,MotherBoard,Storage,PowerSupply,RAM,GraphicsCard,Case")] CustomMade customMade)
        {
            if (ModelState.IsValid)
            {
                db.customMades.Add(customMade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customMade);
        }

        [Authorize(Roles = "Administrator, Seller")]
        // GET: CustomMades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomMade customMade = db.customMades.Find(id);
            if (customMade == null)
            {
                return HttpNotFound();
            }
            return View(customMade);
        }

        // POST: CustomMades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator, Seller")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ImgURL,Price,Processor,MotherBoard,Storage,PowerSupply,RAM,GraphicsCard,Case")] CustomMade customMade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customMade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customMade);
        }

        [Authorize(Roles = "Administrator, Seller")]
        // GET: CustomMades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomMade customMade = db.customMades.Find(id);
            if (customMade == null)
            {
                return HttpNotFound();
            }
            return View(customMade);
        }

        [Authorize(Roles = "Administrator, Seller")]
        // POST: CustomMades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomMade customMade = db.customMades.Find(id);
            db.customMades.Remove(customMade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proekt2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proekt2.Models;
using PagedList;

namespace Proekt2.Controllers
{
    public class ProductsController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index(string searchString, string currentFilter, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var products = db.Products.ToList();
            if (!(String.IsNullOrEmpty(searchString)))
            {
                searchString = searchString.ToLower();
                products = db.Products.Where(product => product.Name.ToLower().Contains(searchString)).ToList();
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return View(products.ToPagedList(pageNumber, pageSize));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [Authorize(Roles = "Administrator, Seller")]
        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "Administrator, Seller")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ImgURL,ShortDescription,LongDescription,Price,InStock,Category,Manufacturer")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5

        [Authorize(Roles = "Administrator, Seller")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize(Roles = "Administrator, Seller")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ImgURL,ShortDescription,LongDescription,Price,InStock,Category,Manufacturer")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }


        [Authorize(Roles = "Administrator, Seller")]
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }


        [Authorize(Roles = "Administrator, Seller")]
        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proekt2/Views/CustomMades/Create.cshtml
@model Proekt2.Models.CustomMade

@{
    ViewBag.Title = "Create";
}

<html>
<head>
    <style>
        .btn-primary {
            color: #fff;
            background-color: #128FC8;
            border-color: #128FC8;
        }
    </style>
</head>
<body>

    <div class="container py-4">
        <h2 class="text-center">Add a new PC component</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4 class="pt-3 text-center">Enter the following components and click on the „Create“ button. If you change your mind, click on the „Back to List“ button.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.ImgURL, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.ImgURL, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.ImgURL, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.Processor, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Processor, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Processor, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.MotherBoard, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.MotherBoard, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.MotherBoard, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.Storage, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Storage, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.PowerSupply, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.PowerSupply, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.PowerSupply, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.RAM, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.GraphicsCard, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.GraphicsCard, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.GraphicsCard, "", new { @class = "text-danger" })
                </div>

                <div class="form-group  my-2">
                    @Html.LabelFor(model => model.Case, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Case, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Case, "", new { @class = "text-danger" })
                </div>

                <div class="d-flex">
                    <input type="submit" value="Create" class="btn btn-primary mt-3 py-2 px-4 me-3" />
                    @Html.ActionLink("Back to List", "Index", "CustomMades", new { }, new { @class = "btn btn-primary mt-3 py-2 px-4" })
                </div>
            </div>
        }

        <div>

        </div>

    </div>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proekt2/Views/CustomMades/Edit.cshtml
@model Proekt2.Models.CustomMade

@{
    ViewBag.Title = "Edit";
}




<html>

<head>

    <style>
        .btn-primary {
            color: #fff;
            background-color: #128FC8;
            border-color: #128FC8;
        }
    </style>
</head>

<body>
    <div class="container py-4">
        <h2 class="text-center">You are currently editing: @Model.Name</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4 class="pt-3 text-center">Edit the product and click on the „Edit“ button. If you change your mind then click on the „Back to List“ button.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.ImgURL, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.ImgURL, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.ImgURL, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Processor, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Processor, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Processor, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.MotherBoard, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.MotherBoard, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.MotherBoard, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Storage, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Storage, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Storage, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.PowerSupply, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.PowerSupply, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.PowerSupply, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.RAM, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.RAM, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.RAM, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.GraphicsCard, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.GraphicsCard, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.GraphicsCard, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Case, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Case, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Case, "", new { @class = "text-danger" })
                </div>

                <div class="form-group my-2">
                    @Html.LabelFor(model => model.Case, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Case, new { htmlAttributes = new { @class = "form-control w-100" } })
                    @Html.ValidationMessageFor(model => model.Case, "", new { @class = "text-danger" })
                </div>

                <div class="d-flex">
                    <input type="submit" value="Save" class="btn btn-primary mt-3 py-2 px-4 me-3" />
                    @Html.ActionLink("Back to List", "Index", "CustomMades", new { }, new { @class = "btn btn-primary mt-3 py-2 px-4" })
                </div>


            </div>
        }

        <div>

        </div>
    </div>
</body>
</html>
<div>
    @Html.ActionLink("Back to List", "Index", "Products")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proekt2/Views/CustomMades/Index.cshtml
@model IEnumerable<Proekt2.Models.CustomMade>

@{
    ViewBag.Title = "Index";
}

<html>

<head>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    <style>

        body {
            font-family: 'Poppins', sans-serif;
        }

        .wide-pic {
            padding: 2rem 1rem;
            margin-bottom: 2rem;
            background-color: #e9ecef;
            background-repeat: no-repeat;
            background-size: cover;
            background: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)), url(https://c8.alamy.com/comp/2GA76G7/wide-banner-of-parts-and-components-for-modern-desktop-computer-mainboard-power-supply-ram-ssd-hard-disk-cpu-cooler-graphics-card-and-midi-tower-pc-c-2GA76G7.jpg);
        }

        .btn-primary {
            color: #fff;
            background-color: #128FC8;
            border-color: #128FC8;
        }

        

        .text-primary {
            color: #128FC8 !important;
        }

        .card:hover {
            cursor: pointer;
        }

        .card {
            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.2);
        }

        .team img {
            position: relative;
            z-index: 1;
        }

        .team .team-text {
            position: relative;
            width: 100%;
            height: 100px;
            bottom: 0px;
            left: 0;
            border-bottom: 5px solid #128FC8;
            transition: .5s;
        }

        .team:hover .team-text {
            bottom: 100px;
        }

        .team .team-social {
            position: absolute;
            width: 100%;
            height: 100px;
            bottom: -100px;
            left: 0;
            transition: .5s;
        }

        .team:hover .team-social {
            bottom: 0;
        }

        .bg-primary {
            background-color: #128FC8 !important;
        }

        .bg-secondary {
            background-color: #F2F2F4 !important;
        }
    </style>
</head>

<body>

    <div class="wide-pic mb-5 h-auto">
        <div class="container text-center py-5">
            <h1 class="text-white display-3">Start building your PC now!</h1>
                    <a class="text-white" href="" style="text-decoration: none;">
                        Select as many PC components as you like and put them in your shopping cart.
                    </a>
        </div>
    </div>

    <div class="container">
        <h2 class="text-center">Select a product and add it to your shopping cart</h2>

        <hr />


    </div>

    <div class="container-fluid pt-5 mb-5">
        <div class="container">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-lg-3 col-md-6">
                        <div class="team card position-relative overflow-hidden border-0 mb-5">
                            <img class="card-img-top" src="@item.ImgURL" alt="">
                            <div class="card-body text-center p-0">
                                <div class="team-text d-flex flex-column justify-content-center bg-secondary  ">
                                    <h5 class="font-weight-bold">@item.Name </h5>
                                    <span>$@item.Price,99</span>
                                </div>
                                <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                                    @Html.ActionLink("Edit", "Edit", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social mr-2" })
                                    @Html.ActionLink("Details", "Details", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social mr-2" })
                                    @Html.ActionLink("Delete", "Delete", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social mr-2" })
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>


</body>
</html>

Proekt2/Views/CustomMades/PreBuiltPC.cshtml
@model IEnumerable<Proekt2.Models.CustomMade>

@{
    ViewBag.Title = "Index";
}

<html>

<head>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    <style>

        body {
            font-family: 'Poppins', sans-serif;
        }

        .custom-made-pc{
            font-weight: 800;
        }

        .jumbotron {
            padding: 2rem 1rem;
            margin-bottom: 2rem;
            background-color: #e9ecef;
            background-repeat: no-repeat;
            background-size: cover;
            background: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)), url(https://c8.alamy.com/comp/2GA76G7/wide-banner-of-parts-and-components-for-modern-desktop-computer-mainboard-power-supply-ram-ssd-hard-disk-cpu-cooler-graphics-card-and-midi-tower-pc-c-2GA76G7.jpg);
        }

        .btn-primary {
            color: #fff;
            background-color: #128FC8;
            border-color: #128FC8;
        }

        .jumbotron-fluid {
            padding-right: 0;
            padding-left: 0;
        }

        .text-primary {
            color: #128FC8 !important;
        }

        .card:hover {
            cursor: pointer;
        }

        .card {
            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.2);
        }

        .team img {
            position: relative;
            z-index: 1;
        }

        .team .team-text {
            position: relative;
            width: 100%;
            height: 100px;
            bottom: 0px;
            left: 0;
            border-bottom: 5px solid #128FC8;
            transition: .5s;
        }

        .team:hover .team-text {
            bottom: 100px;
        }

        .team .team-social {
            position: absolute;
            width: 100%;
            height: 100px;
            bottom: -100px;
            left: 0;
            transition: .5s;
        }

        .team:hover .team-social {
            bottom: 0;
        }

        .bg-primary {
            background-color: #128FC8 !important;
        }

        .bg-secondary {
            background-color: #F2F2F4 !important;
        }
    </style>
</head>

<body>

    <div class="container-fluid pt-5 mb-5">
        <div class="container">
            <div class="text-center pb-2">
                <h4 class="text-primary text-uppercase font-weight-bold custom-made-pc">Custom made PC</h4>
                <p>
                    If you don't have time to built a PC on your own, you can check one of these custom made PC's.
                </p>
                <hr />
            </div>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-lg-3 col-md-6">
                        <div class="team card position-relative overflow-hidden border-0 mb-5">
                            <img class="card-img-top" src="@item.ImgURL" alt="">
                            <div class="card-body text-center p-0">
                                <div class="team-text d-flex flex-column justify-content-center bg-secondary  ">
                                    <h5 class="font-weight-bold">@item.Name </h5>
                                    <span>$@item.Price,99</span>
                                </div>
                                <div class="team-social d-flex align-items-center justify-content-center bg-primary">
                                    @if (User.IsInRole("Administrator") || User.IsInRole("Seller"))
                                    {
                                        @Html.ActionLink("Edit", "Edit", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social ms-2 me-2" })
                                    }
                                    @Html.ActionLink("Details", "Details", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social me-2" })
                                   
                                    @if (User.IsInRole("Administrator") || User.IsInRole("Seller"))
                                    {
                                        @Html.ActionLink("Delete", "Delete", "CustomMades", new { id = item.Id }, new { @class = "btn btn-outline-dark btn-social me-2" })
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>


</body>
</html>